name: test-html-scraper
run-name: Running unit tests for the html-scraper
on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "scraper/html-scraper/**"
      - "!scraper/html-scraper/**.md"
      - "raw-input-data/**"

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install dependencies
        working-directory: ./scraper/html-scraper/
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[test]"

      - name: Test with pytest
        working-directory: ./scraper/html-scraper/
        run: |
          pytest --cache-clear -m "not (slow or profiling)"

      - name: Test slow test suites
        working-directory: ./scraper/html-scraper/
        run: |
          pytest -m "slow" --cov-append
        if: startsWith(matrix.os, 'ubuntu-')
